TimeTracker/Controllers/AssignmentController.cs
using DataLayer.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TimeTracker.BizLayer;
using TimeTracker.Models.Dto;

namespace TimeTracker.Controllers
{
	public class AssignmentController : Controller
	{
		private readonly ITimeTrackerService _timeTrackerService;

		public AssignmentController(ITimeTrackerService timeTrackerService)
		{
			_timeTrackerService = timeTrackerService;
		}
		// GET: AssignmentController
		public async Task<ActionResult> Index()
		{
			try
			{
				IEnumerable<AssignmentDto> assignments = await _timeTrackerService.GetAssignmentsAsync(User, null, null);
				return View(assignments);
			}
			catch (Exception ex)
			{
				//Log this error;
				return View(ex);
			}
	
		}

		// GET: AssignmentController/Details/5
		public async Task<ActionResult> Details(Guid id)
		{
			AssignmentDto assignment = await _timeTrackerService.GetAssignmentAsync(User,id);
			return View(assignment);
		}

		// GET: AssignmentController/Create
		public async Task<ActionResult> Create(Guid? id)
		{
			var viewModel = await _timeTrackerService.CreateAssignmentAsync(User);

			if(id.HasValue)
			{
				var item = viewModel.ContractList.Where(x => Guid.Parse(x.Value) == id).First();
				item.Selected = true;
				viewModel.ContractId = Guid.Parse(item.Value);
			}


			return View(viewModel);
		}

		// POST: AssignmentController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create([Bind("ContractId", "CompanyId", "Description", "MinutesAvailable","IsActive")]AssignmentDto assignmentDto)
		{
			try
			{
				await _timeTrackerService.CreateAssignmentAsync(User, assignmentDto);
				return RedirectToAction(nameof(Index));
			}
			catch(Exception ex)
			{
				return View();
			}
		}

		// GET: AssignmentController/Edit/5
		public async Task<ActionResult> Edit(Guid id)
		{
			try
			{
				AssignmentDto assignment = await _timeTrackerService.UpdateAssignmentAsync(User, id);
				return View(assignment);
			}
			catch(Exception ex)
			{
				return RedirectToAction(nameof(Index));
			}
		}

		// POST: AssignmentController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(Guid id, AssignmentDto assignmentDto)
		{
			try
			{
				await _timeTrackerService.UpdateAssignmentAsync(User,id, assignmentDto);
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: AssignmentController/Delete/5
		public async Task<ActionResult> Delete(int id)
		{
			return View();
		}

		// POST: AssignmentController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

TimeTracker/Controllers/ContractController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TimeTracker.BizLayer;
using TimeTracker.Models.Dto;

namespace TimeTracker.Controllers
{
	public class ContractController : Controller
	{
		private readonly ITimeTrackerService _timeTrackerService;

		public ContractController(ITimeTrackerService timeTrackerService)
		{
			_timeTrackerService = timeTrackerService;
		}
	
		// GET: ContractController
		public async Task<ActionResult> Index()
		{
			var contracts = await _timeTrackerService.GetContractsAsync(this.User);
			return View(contracts);
		}

		// GET: ContractController/Details/5
		public async Task<ActionResult> Details(Guid id)
		{
			ContractDto contract = await _timeTrackerService.GetContractAsync(this.User,id);
			return View(contract);
		}

		// GET: ContractController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: ContractController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create([Bind("CompanyName", "Description", "HourlyRate", "StartDate")]ContractDto contractDto)
		{
			try
			{
				if (ModelState.IsValid)
				{
					await _timeTrackerService.CreateContractAsync(User, contractDto);
					return RedirectToAction(nameof(Index));
				}
				return View();
			}
			catch(Exception ex)
			{
				return View();
			}
		}

		// GET: ContractController/Edit/5
		public async Task<ActionResult> Edit(Guid id)
		{
			ContractDto contract = await _timeTrackerService.GetContractAsync(this.User, id);
			return View(contract);
		}

		// POST: ContractController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(Guid id, 
				[Bind ("CompanyName", "Description", "HourlyRate", "StartDate","EndDate", "IsActive")] ContractDto contractDto)
		{
			try
			{
				if(ModelState.IsValid)
				{
					await _timeTrackerService.UpdateContractAsync(User,id,contractDto);
					return RedirectToAction(nameof(Index));
				}
				return View();
			}
			catch(Exception ex)
			{
				return View();
			}
		}

		// GET: ContractController/Delete/5
		public async Task<ActionResult> Delete(int id)
		{
			return View();
		}

		// POST: ContractController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

TimeTracker/Controllers/EffortController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TimeTracker.BizLayer;
using TimeTracker.Models.Dto;

namespace TimeTracker.Controllers
{
	public class EffortController : Controller
	{
		private readonly ITimeTrackerService _timeTrackerService;

		public EffortController(ITimeTrackerService timeTrackerService)
		{
			_timeTrackerService = timeTrackerService;
		}
		// GET: EffortController
		public async Task<ActionResult> Index()
		{
			IEnumerable<TimeTracker.Models.Dto.EffortDto> efforts = await _timeTrackerService.GetEffortsAsync(User,null,null);
			return View(efforts);
		}

		// GET: EffortController/Details/5
		public async Task<ActionResult> Details(Guid id)
		{
			EffortDto effortDto = await _timeTrackerService.GetEffortAsync(User, id);
			return View(effortDto);
		}

		// GET: EffortController/Create
		public async Task<ActionResult> Create(Guid? id)
		{
			EffortDto dto = new EffortDto();
			IEnumerable<AssignmentDto> assignments = new List<AssignmentDto>();

			//Get available assignments

			if(id.HasValue)
			{
				dto.AssignmentId = id.Value;
				var assignment = await _timeTrackerService.GetAssignmentAsync(User, id.Value);
				dto.AssignmentSelectList = assignment.ContractAssignmentList;
				dto.AssignmentDescription = assignment.Description;
			}
			else
			{
				assignments = await _timeTrackerService.GetAssignmentsAsync(User,null);
				dto.AssignmentSelectList = assignments.First().ContractAssignmentList;
			}
				

			dto.WorkDate = new DateTime(DateTime.Now.Year,DateTime.Now.Month,DateTime.Now.Day);
			dto.StartTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
			dto.EndTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);

			return View(dto);
		}

		// POST: EffortController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(EffortDto effortDto)
		{
			try
			{
				await _timeTrackerService.CreateEffortAsync(User, effortDto);
				return RedirectToAction(nameof(Index));
			}
			catch(Exception ex)
			{
				return View();
			}
		}

		// GET: EffortController/Edit/5
		public async Task<ActionResult> Edit(Guid id)
		{
			EffortDto effortDto = await _timeTrackerService.GetEffortAsync(User, id);
			return View(effortDto);
		}

		// POST: EffortController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(Guid id, EffortDto effortDto)
		{
			try
			{
				await _timeTrackerService.UpdateEffortAsync(User,id,effortDto);
				return RedirectToAction(nameof(Index));
			}
			catch(Exception ex)
			{
				return View();
			}
		}

		// GET: EffortController/Delete/5
		public async Task<ActionResult> Delete(Guid id)
		{
			EffortDto effortDto = await _timeTrackerService.GetEffortAsync(User, id);
			return View(effortDto);
		}

		// POST: EffortController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(Guid id,EffortDto effortDto)
		{
			try
			{
				await _timeTrackerService.DeleteEffortAsync(User, id, false);
				return RedirectToAction(nameof(Index));
			}
			catch(Exception ex)
			{
				return View();
			}
		}
	}
}

TimeTracker/Controllers/ReportController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TimeTracker.BizLayer;
using TimeTracker.Models;

namespace TimeTracker.Controllers
{
	public class ReportController : Controller
	{
		private readonly ITimeTrackerService _timeTrackerService;

		public ReportController(ITimeTrackerService timeTrackerService)
		{
			_timeTrackerService = timeTrackerService;
		}

		// GET: ReportController/Create
		public async Task<ActionResult> Create()
		{
			var model = new ReportViewModel();
			model.ContractList = await _timeTrackerService.GetContractSelectListAsync(User);
			
			return View(model);
		}

		// POST: ReportController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(ReportViewModel m)
		{
			try
			{
				//if (ModelState.IsValid)
				//{
					MemoryStream ms = await _timeTrackerService.CreateExcelReportAsync(User, m.ContractId, m.Start, m.End);
					return File(ms, "APPLICATION/octet-stream", "HoursReport.xlsx");
				//}
				return View();
			}
			catch(Exception ex)
			{
				return View();
			}
		}
	}
}

TimeTracker/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - TimeTracker</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/TimeTracker.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimeTracker</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					@if (SignInManager.IsSignedIn(User))
					{
						<ul class="navbar-nav flex-grow-1">
							@*<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>*@
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Contract" asp-action="Index">Contract</a>
						</li>
						
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="Index">Assignment</a>
						</li>
						
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Effort" asp-action="Index">Effort</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Create">Run Report</a>
						</li>
					</ul>
					}
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - TimeTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>